name: CI

on:
  push:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-2b1f8d6dd90f9790faf0528e05e60e573a7569ce

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt
        id: fmt

      - name: Run Soldeer Install
        run: |
          forge soldeer install
          cd dependencies/@fdk-0.3.0-beta && forge soldeer install && cd ../..

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
